owner: apunto-io
repo: apunto-status

sites:
  - name: Apunto App
    url: https://control.apunto.io/up
    maxResponseTime: 2000
    icon: https://raw.githubusercontent.com/apunto-io/apunto-status/master/assets/apunto_logo.png
    assignees:
      - JNajera
  - name: Apunto Alpha
    url: https://alpha.apunto.io/up
    maxResponseTime: 2000
    icon: https://raw.githubusercontent.com/apunto-io/apunto-status/master/assets/apunto_logo.png
    assignees:
      - JNajera

status-website:
  cname: status.apunto.io
  logoUrl: https://raw.githubusercontent.com/apunto-io/apunto-status/master/assets/apunto_logo.png
  favicon: https://raw.githubusercontent.com/apunto-io/apunto-status/master/assets/apunto_logo.png
  name: ''
  theme: light
  introTitle: "Sobre este sitio"
  introMessage: Bienvenido al monitor de estatus de Apunto. Aquí encontrarás información en tiempo real sobre el estado de nuestros servicios.
  navbar:
    - title: Estatus
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Trigger Setup CI workflow - Force execution
