# Change these first
owner: apunto-io # Your GitHub organization or username, where this repository lives
repo: apunto-status # The name of this repository

sites:
  - name: Apunto Control
    url: https://control.apunto.io/up

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.apunto.io
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Apunto Status
  introTitle: "**Apunto** - Estado del Sistema"
  introMessage: Monitoreo en tiempo real del estado de los servicios de Apunto. Todos los datos se actualizan automáticamente desde nuestro [repositorio de GitHub](https://github.com/apunto-io/apunto-status).
  navbar:
    - title: Estado
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
